# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4ei0ZO_zrtYH2fqXFKC69IGSSNuu4h7
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# Tytuł aplikacji w Streamlit
st.title("Mikołaj generowany w Matplotlib 🎅")

def draw_santa():
    # 1. Konfiguracja wykresu
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.set_aspect('equal')

    # Ukrywamy osie
    ax.axis('off')

    # Tło (jasnoniebieskie niebo)
    ax.set_facecolor('#87CEEB')
    rect_sky = patches.Rectangle((0, 0), 100, 100, color='#87CEEB')
    ax.add_patch(rect_sky)

    # 2. Śnieg na ziemi
    snow_ground = patches.Ellipse((50, 0), 120, 40, color='white')
    ax.add_patch(snow_ground)

    # --- RYSOWANIE MIKOŁAJA ---

    # Buty
    ax.add_patch(patches.Rectangle((35, 15), 10, 15, color='black'))
    ax.add_patch(patches.Rectangle((55, 15), 10, 15, color='black'))

    # Tułów (Czerwony płaszcz)
    body = patches.Ellipse((50, 45), 45, 50, color='#D40000')
    ax.add_patch(body)

    # Biały pas na środku płaszcza (pionowy)
    ax.add_patch(patches.Rectangle((46, 25), 8, 45, color='white'))

    # Pas (Czarny)
    belt = patches.Rectangle((28, 40), 44, 8, color='black')
    ax.add_patch(belt)

    # Klamra paska (Złota)
    buckle = patches.Rectangle((45, 40), 10, 8, color='gold', fill=False, linewidth=3)
    ax.add_patch(buckle)

    # Głowa (Skóra)
    head = patches.Circle((50, 70), 12, color='#FFCCB3')
    ax.add_patch(head)

    # Broda (Zbiór białych kółek dla efektu puszystości)
    beard_positions = [(50, 65), (45, 68), (55, 68), (42, 62), (58, 62), (50, 58)]
    for pos in beard_positions:
        ax.add_patch(patches.Circle(pos, 5, color='white'))

    # Oczy
    ax.add_patch(patches.Circle((46, 74), 1.5, color='black'))
    ax.add_patch(patches.Circle((54, 74), 1.5, color='black'))

    # Nos
    ax.add_patch(patches.Circle((50, 71), 2, color='#FF9980'))

    # --- CZAPKA ---
    # Czerwona część
    hat_triangle = patches.Polygon([[35, 78], [65, 78], [50, 95]], closed=True, color='#D40000')
    ax.add_patch(hat_triangle)

    # Białe obszycie czapki
    hat_trim = patches.Rectangle((34, 76), 32, 6, color='white', linewidth=0)
    ax.add_patch(hat_trim)
    ax.add_patch(patches.Circle((34, 79), 3, color='white'))
    ax.add_patch(patches.Circle((66, 79), 3, color='white'))

    # Pompon
    ax.add_patch(patches.Circle((50, 95), 4, color='white'))

    # --- PREZENT I RĘCE ---

    # Ręce (Czerwone rękawy)
    left_arm = patches.Ellipse((30, 50), 20, 10, angle=30, color='#D40000')
    right_arm = patches.Ellipse((70, 50), 20, 10, angle=-30, color='#D40000')
    ax.add_patch(left_arm)
    ax.add_patch(right_arm)

    # Rękawice (Zielone)
    ax.add_patch(patches.Circle((22, 55), 4, color='#228B22')) # Lewa
    ax.add_patch(patches.Circle((78, 55), 4, color='#228B22')) # Prawa

    # Pudełko prezentu (trzymane w prawej ręce)
    gift_x, gift_y = 74, 55
    gift_size = 15
    ax.add_patch(patches.Rectangle((gift_x, gift_y), gift_size, gift_size, color='#32CD32')) # Zielone pudełko

    # Wstążka na prezencie (Czerwona)
    ax.add_patch(patches.Rectangle((gift_x + gift_size/2 - 1, gift_y), 2, gift_size, color='red')) # Pionowa
    ax.add_patch(patches.Rectangle((gift_x, gift_y + gift_size/2 - 1), gift_size, 2, color='red')) # Pozioma

    # 3. Dodanie padającego śniegu (losowe kropki)
    # Usunąłem seed(42), żeby przy każdym odświeżeniu strony śnieg padał w innym miejscu (dla efektu)
    snow_x = np.random.uniform(0, 100, 50)
    snow_y = np.random.uniform(20, 100, 50)
    ax.scatter(snow_x, snow_y, color='white', s=30, marker='*')

    ax.set_title("Wesołych Świąt!", fontsize=16, color='#D40000', fontweight='bold')

    # WAŻNE: Zwracamy obiekt figury, zamiast używać plt.show() wewnątrz funkcji
    return fig

# Wywołanie funkcji i wyświetlenie w Streamlit
figura = draw_santa()
st.pyplot(figura)